name: Install dependencies
description: Install node modules or pull them from cache

inputs:
  environment:
    description: Additional cache key
    default: development

runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ inputs.environment }}-dependencies-${{ hashFiles('package-lock.json') }}
    - name: Install dev dependencies
      if: ${{ inputs.environment }} == 'development' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
    - name: Install prod dependencies
      if: ${{ inputs.environment }} == 'production' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --production
