FROM node:16-alpine

WORKDIR /service

COPY node_modules/ /service/node_modules
COPY package-lock.json package.json /service/

COPY dist/apps/api/credit-api/ /service

USER node

CMD ["node", "main.js"]
