service:
  name: "referral-system-api"

vault:
  secretConfig: "database/creds/referral-system-api"
  templateConfig: |+
    {{- with secret "database/creds/referral-system-api"}}
    export TYPEORM_USERNAME="{{ .Data.username }}"
    export TYPEORM_PASSWORD="{{ .Data.password }}"
    {{- end }}
    {{- with secret "kv/data/database" }}
    export TYPEORM_PORT="{{ .Data.data.port }}"
    export TYPEORM_HOST="{{ .Data.data.hostname }}"
    {{- end }}
    export TYPEORM_DATABASE="referral-system-api"
    {{- with secret "kv/data/queue" }}
    export QUEUE_URL="{{ .Data.data.url }}"
    {{- end }}
    {{- with secret "kv/data/referral-system-api" }}
    export ENCRYPTION_KEY='{{ .Data.data.encryption_key }}'
    {{- end }}

autoscaling:
  queue: false