export const SERVICE_NAME = 'user-api';
export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`;

export enum ConfigVariables {
  AUTH0_DOMAIN = 'AUTH0_DOMAIN',
  AUTH0_AUDIENCE = 'AUTH0_AUDIENCE',
  AUTH0_M2M_CLIENT_ID = 'AUTH0_M2M_CLIENT_ID',
  AUTH0_M2M_CLIENT_SECRET = 'AUTH0_M2M_CLIENT_SECRET',
  AUTH0_M2M_DOMAIN = 'AUTH0_M2M_DOMAIN',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  INTERNAL_API_URL = 'INTERNAL_API_URL',
  QUEUE_URL = 'QUEUE_URL',
  ENCRYPTION_KEY = 'ENCRYPTION_KEY',
}

export const KYC_SUBMITTED_TOPIC = 'user.kyc.submitted';

export const EMAIL_VERIFIED_TOPIC = 'user.email.verified';

export const MFA_ENROLLED_TOPIC = 'user.mfa.enrolled';
