apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-api
  labels:
    app: mail-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'mail-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: mail-api
  {{- if not .Values.local }}
  {{- if eq .Values.environment "production" }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mail-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'mail-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
      {{- if not .Values.local }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "mail-api"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/mail-api"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "database/creds/mail-api"}}
          export TYPEORM_USERNAME="{{ .Data.username }}"
          export TYPEORM_PASSWORD="{{ .Data.password }}"
          {{- end }}
          {{- with secret "kv/data/database" }}
          export TYPEORM_PORT="{{ .Data.data.port }}"
          export TYPEORM_HOST="{{ .Data.data.hostname }}"
          {{- end }}
          export TYPEORM_DATABASE="mail-api"
          {{- with secret "kv/data/queue" }}
          export QUEUE_URL="{{ .Data.data.url }}"
          {{- end }}
          {{- with secret "kv/data/mail-api" }}
          export ENCRYPTION_KEY="{{ .Data.data.encryption_key }}"
          export SENDGRID_API_URL="{{ .Data.data.sendgrid_api_url }}"
          export SENDGRID_MAILING_LIST_ID="{{ .Data.data.sendgrid_mailing_list_id }}"
          export SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID="{{ .Data.data.sendgrid_verify_email_template_id }}"
          export SENDGRID_MARGIN_CALL_EXITED_TEMPLATE_ID="{{ .Data.data.sendgrid_margin_call_exited_template_id }}"
          export SENDGRID_MARGIN_CALL_REACHED_TEMPLATE_ID="{{ .Data.data.sendgrid_margin_call_reached_template_id }}"
          export SENDGRID_MARGIN_CALL_IN_DANGER_TEMPLATE_ID="{{ .Data.data.sendgrid_margin_call_in_danger_template_id }}"
          export SENDGRID_COLLATERAL_LIQUIDATED_TEMPLATE_ID="{{ .Data.data.sendgrid_collateral_liquidated_template_id }}"
          export SENDGRID_CONNECT_SALES_TEMPLATE_ID="{{ .Data.data.sendgrid_connect_sales_template_id }}"
          export ARCHIE_MARKETING_WEBSITE_URL="{{ .Data.data.marketing_website_url }}"
          {{- end }}
          `}}
      {{- end }}
    spec:
      serviceAccountName: mail-api
      containers:
        - name: mail-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          args:
            ['sh', '-c', '. /vault/secrets/config && node service/main.js']
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          {{- if not .Values.local }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_LOGS_INJECTION
              value: 'true'
          {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mail-api-service
  labels:
    app: mail-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mail-api
