apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-api
  labels:
    app: mail-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'mail-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: mail-api
  {{- if not .Values.local }}
  {{- if eq .Values.environment "production" }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mail-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'mail-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
    spec:
      containers:
        - name: mail-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          {{- if not .Values.local }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_LOGS_INJECTION
              value: 'true'
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: db-username
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: db-password
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: db-hostname
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: db-port
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: db-database
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-api-key
            - name: SENDGRID_API_URL
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-api-url
            - name: SENDGRID_MAILING_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-mailing-list-id
            - name: SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-verify-email-template-id
            - name: SENDGRID_MARGIN_CALL_EXITED_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-margin-call-exited-template-id
            - name: SENDGRID_MARGIN_CALL_REACHED_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-margin-call-reached-template-id
            - name: SENDGRID_MARGIN_CALL_IN_DANGER_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-margin-call-in-danger-template-id
            - name: SENDGRID_COLLATERAL_LIQUIDATED_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-collateral-liquidated-template-id
            - name: SENDGRID_CONNECT_SALES_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: sendgrid-connect-sales-template-id
            - name: ARCHIE_MARKETING_WEBSITE_URL
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: marketing-website-url
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: queue-shared-secrets
                  key: queue-url
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: mail-api-secrets
                  key: encryption-key
          {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: mail-api-service
  labels:
    app: mail-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mail-api
