name: 'Docker prebuild'
description: 'Prebuild docker image and cache layers'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Prebuild dockerfile
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: false
        file: ./.github/actions/docker-prebuild/Dockerfile
        cache-from: type=gha, scope=${{ github.sha }}
        cache-to: type=gha, scope=${{ github.sha }}