name: 'Docker prebuild'
description: 'Prebuild docker image and cache layers'

runs:
  using: composite
  steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Prebuild dockerfile
      shell: bash
      run: docker build -f ./.github/actions/docker-prebuild/Dockerfile .
