FROM node:16-alpine
WORKDIR /service

COPY dist/apps/mail-api/ /service
COPY node_modules/ /service/node_modules
COPY package-lock.json /service/
COPY package.json /service/

USER node

CMD ["node", "main.js"]
