apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  {{- if eq .Values.environment "production" }}
  name: production-ingress
  {{- else }}
  name: test-ingress
  {{- end }}
  annotations:
    {{- if .Values.local }}
    kubernetes.io/ingress.class: nginx
    {{- else }}
    alb.ingress.kubernetes.io/group.name: test
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    {{- if eq .Values.environment "production" }}
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:248649311686:certificate/676861e0-ab15-4cc1-afae-67ff9e8a41f0
    {{- else }}
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:108827241267:certificate/25948e51-ba06-4736-9396-d591481e72f7
    {{- end }}
    {{- end }}
spec:
  rules:
    {{- if .Values.local }}
    - http:
    {{- else if eq .Values.environment "production" }}
    - host: 'api.archie.finance'
      http:
    {{- else }}
    - host: 'api.dev.archie.finance'
      http:
    {{- end }}
        paths:
          ## Asset price api service
          - path: /v1/asset_price
            pathType: Prefix
            backend:
              service:
                name: archie-asset-price-api-service
                port:
                  number: 80
          ## User api service
          - path: /v1/email_waitlist
            pathType: Prefix
            backend:
              service:
                name: archie-user-api-service
                port:
                  number: 80
          - path: /v1/kyc
            pathType: Prefix
            backend:
              service:
                name: archie-user-api-service
                port:
                  number: 80
          - path: /v1/user
            pathType: Prefix
            backend:
              service:
                name: archie-user-api-service
                port:
                  number: 80
          ## Collateral api service
          - path: /v1/deposit_address
            pathType: Prefix
            backend:
              service:
                name: archie-collateral-api-service
                port:
                  number: 80
          - path: /v1/fireblocks/webhook
            pathType: Prefix
            backend:
              service:
                name: archie-collateral-api-service
                port:
                  number: 80
          ## Onboarding api service
          - path: /v1/onboarding
            pathType: Prefix
            backend:
              service:
                name: archie-onboarding-api-service
                port:
                  number: 80
          ## Credit api service
          - path: /v1/credit
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          - path: /v1/collateral
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          - path: /v1/margins
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          - path: /v1/apto
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          - path: /v1/rize/users
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          - path: /v1/plaid
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          ## Referral system service
          - path: /v1/waitlist
            pathType: Prefix
            backend:
              service:
                name: archie-referral-system-api-service
                port:
                  number: 80
          ## Peach api service
          - path: /v1/loans
            pathType: Prefix
            backend:
              service:
                name: archie-peach-api-service
                port:
                  number: 80
