apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  {{- if eq .Values.environment "production" }}
  name: archie-production-internal-ingress
  {{- else }}
  name: archie-development-internal-ingress
  {{- end }}
  annotations:
    {{- if .Values.local }}
    kubernetes.io/ingress.class: nginx
    {{- else }}
    {{- if eq .Values.environment "production" }}
    alb.ingress.kubernetes.io/group.name: archie-production
    {{- else }}
    alb.ingress.kubernetes.io/group.name: archie-development
    {{- end }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    {{- end }}
spec:
  rules:
    - http:
        paths:
          ## User api service
          - path: /internal/kyc
            pathType: Prefix
            backend:
              service:
                name: archie-user-api-service
                port:
                  number: 80
          ## Onboarding api service
          - path: /internal/onboarding
            pathType: Prefix
            backend:
              service:
                name: archie-onboarding-api-service
                port:
                  number: 80
          - path: /internal/margins
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          ## User api service
          - path: /internal/user
            pathType: Prefix
            backend:
              service:
                name: archie-user-api-service
                port:
                  number: 80
          ## Webhook api service
          - path: /internal/webhook
            pathType: Prefix
            backend:
              service:
                name: archie-webhook-api-service
                port:
                  number: 80
          # Ltv api
          - path: /internal/ltv/periodic_check
            pathType: Prefix
            backend:
              service:
                name: archie-ltv-api-service
                port:
                  number: 80
          # Ledger api
          - path: /internal/ledger
            pathType: Prefix
            backend:
              service:
                name: archie-ledger-api-service
                port:
                  number: 80
