apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: archie-development-internal-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: archie-development
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
spec:
  rules:
    - http:
        paths:
          ## Onboarding api service
          - path: /internal/onboarding
            pathType: Prefix
            backend:
              service:
                name: archie-onboarding-api-service
                port:
                  number: 80
          ## Credit api service
          - path: /internal/credit
            pathType: Prefix
            backend:
              service:
                name: archie-credit-api-service
                port:
                  number: 80
          ## Asset price api service
          - path: /internal/asset_price
            pathType: Prefix
            backend:
              service:
                name: archie-asset-price-api-service
                port:
                  number: 80
          ## Collateral api service
          - path: /internal/collateral
            pathType: Prefix
            backend:
              service:
                name: archie-collateral-api-service
                port:
                  number: 80