export const SERVICE_NAME = 'asset-price-api';
export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`;

export enum ConfigVariables {
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  COINGECKO_API_URI = 'COINGECKO_API_URI',
  ASSET_LIST = 'ASSET_LIST',
  QUEUE_URL = 'QUEUE_URL',
}

export const GET_ASSET_PRICES_RPC = 'get.asset_prices.rpc';
