export const SERVICE_NAME = 'mail-api';
export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`;

export enum ConfigVariables {
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_MAILING_LIST_ID = 'SENDGRID_MAILING_LIST_ID',
  SENDGRID_API_URL = 'SENDGRID_API_URL',
  SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID = 'SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID',
  ARCHIE_MARKETING_WEBSITE_URL = 'ARCHIE_MARKETING_WEBSITE_URL',
  QUEUE_URL = 'QUEUE_URL',
  INTERNAL_API_URL = 'INTERNAL_API_URL',
  SENDGRID_MARGIN_CALL_EXITED_TEMPLATE_ID = 'SENDGRID_MARGIN_CALL_EXITED_TEMPLATE_ID',
  SENDGRID_MARGIN_CALL_REACHED_TEMPLATE_ID = 'SENDGRID_MARGIN_CALL_REACHED_TEMPLATE_ID',
  SENDGRID_MARGIN_CALL_IN_DANGER_TEMPLATE_ID = 'SENDGRID_MARGIN_CALL_IN_DANGER_TEMPLATE_ID ',
  SENDGRID_COLLATERAL_LIQUIDATED_TEMPLATE_ID = 'SENDGRID_COLLATERAL_LIQUIDATED_TEMPLATE_ID ',
}
