export const SERVICE_NAME = 'credit-line-api';
export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`;

export enum ConfigVariables {
  AUTH0_DOMAIN = 'AUTH0_DOMAIN',
  AUTH0_AUDIENCE = 'AUTH0_AUDIENCE',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  QUEUE_URL = 'QUEUE_URL',
  ASSET_LIST = 'ASSET_LIST',
  RUN_MIGRATIONS = 'RUN_MIGRATIONS',
}

export const CREDIT_LINE_CREATED_TOPIC = 'credit_line.created';
export const CREDIT_LINE_UPDATED_TOPIC = 'credit_line.updated';
