export enum AssetType {
  ERC20 = 'ERC20',
  SOL = 'SOL',
  BTC = 'BTC',
}

export interface AssetList {
  [key: string]: AssetInformation;
}

export interface AssetInformation {
  fireblocks_id: string;
  coinapi_id: string;
  network: AssetType;
}

export enum ConfigVariables {
  AUTH0_DOMAIN = 'AUTH0_DOMAIN',
  AUTH0_AUDIENCE = 'AUTH0_AUDIENCE',
  AUTH0_M2M_CLIENT_ID = 'AUTH0_M2M_CLIENT_ID',
  AUTH0_M2M_CLIENT_SECRET = 'AUTH0_M2M_CLIENT_SECRET',
  AUTH0_M2M_DOMAIN = 'AUTH0_M2M_DOMAIN',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_MAILING_LIST_ID = 'SENDGRID_MAILING_LIST_ID',
  FIREBLOCKS_VAULT_ACCOUNT_ID = 'FIREBLOCKS_VAULT_ACCOUNT_ID',
  ASSET_LIST = 'ASSET_LIST',
  FIREBLOCKS_API_KEY = 'FIREBLOCKS_API_KEY',
  FIREBLOCKS_PRIVATE_KEY = 'FIREBLOCKS_PRIVATE_KEY',
  FIREBLOCKS_PUBLIC_KEY = 'FIREBLOCKS_PUBLIC_KEY',
  VAULT_PRIVATE_ADDRESS = 'VAULT_PRIVATE_ADDRESS',
  VAULT_USERNAME = 'VAULT_USERNAME',
  VAULT_PASSWORD = 'VAULT_PASSWORD',
  VAULT_NAMESPACE = 'VAULT_NAMESPACE',
}
