service:
  # Set per service
  #name: ""
  command: "node service/main.js"

replicas: 1

resources:
  request:
    memory: "256Mi"
    cpu: '250m'
  limits:
    memory: "292Mi"

autoscaling:
  enabled: true
  memory: true
  cpu: true
  queue: true
  maxReplicas: 3

# Set per service
#vault:
#  secret-config: ""
#  template-config: ""

# Set per service
#cronJobs:
#  curl:
#    - name: 'example'
#      schedule: "* * * * *"
#      command: "curl -X POST ${INTERNAL_API_URL}/api"
