service:
  name: ledger-recalculation-scheduler-api

vault:
  secretConfig: database/creds/ledger-recalculation-scheduler-api
  templateConfig: |+
    {{- with secret "kv/data/database" }}
    export TYPEORM_PORT="{{ .Data.data.port }}"
    export TYPEORM_HOST="{{ .Data.data.hostname }}"
    {{- end }}
    export TYPEORM_DATABASE="ledger-recalculation-scheduler-api"
    {{`{{- with secret "database/creds/ledger-recalculation-scheduler-api"}}
    export TYPEORM_USERNAME="{{ .Data.username }}"
    export TYPEORM_PASSWORD="{{ .Data.password }}"
    {{- end }}
    {{- with secret "kv/data/auth0" }}
    export AUTH0_DOMAIN="{{ .Data.data.domain }}"
    export AUTH0_AUDIENCE="{{ .Data.data.audience }}"
    {{- end }}
    {{- with secret "kv/data/queue" }}
    export QUEUE_URL="{{ .Data.data.url }}"
    {{- end }}
    {{- with secret "kv/data/redis" }}
    export REDIS_URL="{{ .Data.data.url }}"
    {{- end }}
    `}}