apiVersion: apps/v1
kind: Deployment
metadata:
  name: archie-peach-api
  labels:
    app: archie-peach-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'archie-peach-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: archie-peach-api
  {{- if not .Values.local }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: archie-peach-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'archie-peach-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
    spec:
      containers:
        - name: archie-peach-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '256Mi'
              cpu: '300m'
            limits:
              memory: '512Mi'
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_LOGS_INJECTION
              value: 'true'
            {{- if not .Values.local }}
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: domain
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: audience
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: db-username
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: db-password
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: db-hostname
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: db-port
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: db-database
            - name: PEACH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: peach-api-key
            - name: PEACH_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: peach-base-url
            - name: PEACH_COMPANY_ID
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: peach-company-id
            - name: PEACH_BORROWER_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: peach-borrower-role-id
            - name: PEACH_LOAN_ID
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: peach-loan-id
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: queue-shared-secrets
                  key: queue-url
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: peach-api-secrets
                  key: encryption-key
            - name: API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-shared-secrets
                  key: api-base-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-shared-secrets
                  key: redis-url
            {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: archie-peach-api-service
  labels:
    app: archie-peach-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: archie-peach-api
