apiVersion: apps/v1
kind: Deployment
metadata:
  name: archie-onboarding-api
  labels:
    app: archie-onboarding-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'archie-onboarding-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: archie-onboarding-api
  {{- if not .Values.local }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: archie-onboarding-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'archie-onboarding-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
      {{- if not .Values.local }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "onboarding-api"
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/onboarding-api"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`
          {{- with secret "database/creds/onboarding-api" -}}
          export TYPEORM_USERNAME="{{ .Data.username }}"
          export TYPEORM_PASSWORD="{{ .Data.password }}"
          {{- end -}}
          {{- with secret "kv/data/database" -}}
          export TYPEORM_PORT="{{ .Data.data.port }}"
          export TYPEORM_HOST="{{ .Data.data.hostname }}"
          {{- end -}}
          export TYPEORM_DATABASE="onboarding-api"
          {{- with secret "kv/data/auth0" -}}
          export AUTH0_DOMAIN="{{ .Data.data.domain }}"
          export AUTH0_AUDIENCE="{{ .Data.data.audience }}"
          {{- end -}}
          {{- with secret "kv/data/queue" -}}
          export QUEUE_URL="{{ .Data.data.url }}"
          {{- end -}}
          `}}
      {{- end }}
    spec:
      serviceAccountName: onboarding-api
      containers:
        - name: archie-onboarding-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          args:
            ['sh', '-c', '. /vault/secrets/config && node service/main.js']
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          {{- if not .Values.local }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_LOGS_INJECTION
              value: 'true'
          {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: archie-onboarding-api-service
  labels:
    app: archie-onboarding-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: archie-onboarding-api
