datadog:
  apiKey: 'CHANGE_ME'
  appKey: 'CHANGE_ME'
  # criSocketPath: /run/dockershim.sock
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    portEnabled: true
  #  dogstatsd:
  #    useHostPort: true
  kubeStateMetricsEnabled: false # https://github.com/DataDog/helm-charts/issues/415#issuecomment-943117608
  kubeStateMetricsCore:
    enabled: true