apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-stress-test
spec:
  parallelism: 5
  arguments: --out statsd
  script:
    configMap:
      name: stress-test
      file: main.js
  runner:
    image: cudr12/xk6-amqp-linux:latest
    env:
      - name: QUEUE_URL
        value: amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/
      - name: K6_STATSD_ENABLE_TAGS
        value: 'true'
      - name: K6_STATSD_ADDR
        value: datadog:8125
      - name: ONBOARDING_BASE_URL
        value: http://archie-onboarding-api-service:80
      - name: AUTH_BASE_URL
        value: http://archie-utils-test-api-service:80
      - name: CREDIT_LINE_BASE_URL
        value: http://archie-credit-line-api-service:80
