auth:
  postgresPassword: "postgres"
  username: "postgres"
  password: "postgres"
  database: "postgres"
  secretKeys:
    adminPasswordKey: "postgres"
    userPasswordKey: "postgres"
    replicationPasswordKey: "postgres"

primary:
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
  extendedConfiguration: |
    max_connections = 5000