name: 'Set UI configuration'
description: 'Sets environment variables required to build and deploy a project'

inputs:
  projectName:
    description: 'Project name'
    required: true
  environment:
    description: 'Environment'
    required: true

runs:
  using: composite
  steps:
    - name: Configure build environment variables
      shell: bash
      run: |
        npx nx run ${{ inputs.projectName }}:ui-deployment-configuration --environment=${{ inputs.environment }}
