name: Deploy UI
description: Uploads static build to S3 and invalidated cloudfront cache

inputs:
  projectName:
    description: 'Name of the deployment target'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  environment:
    description: 'Environment'
    required: true

runs:
  using: composite
  steps:
    - name: Configure build environment variables
      uses: ./.github/actions/set-ui-configuration
      with:
        projectName: ${{ inputs.projectName }}
        environment: ${{ inputs.environment }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.projectName }}-build
        path: build
    - name: Deploy
      shell: bash
      run: |
        aws s3 sync build s3://${BUCKET_NAME}/
    - name: Invalidate cache
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
