FROM node:16-alpine as builder
WORKDIR /service

ARG LOCAL

COPY . /service

ENV NX_DAEMON=false

RUN npm i
RUN npm run build stress-tests --skip-nx-cache
RUN npm prune --production

FROM node:16-alpine
RUN apk add --no-cache bash

WORKDIR /service

COPY --from=builder /service/package*.json /service/
COPY --from=builder /service/node_modules/ /service/node_modules/
COPY --from=builder /service/dist/apps/tests/stress /service/dist/


CMD ["sleep", "infinity"]