apiVersion: apps/v1
kind: Deployment
metadata:
  name: archie-webhook-api
  labels:
    app: archie-webhook-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'archie-webhook-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: archie-webhook-api
  {{- if not .Values.local }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: archie-webhook-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'archie-webhook-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
      {{- if not .Values.local }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/role: "webhook-api"
        vault.hashicorp.com/agent-requests-cpu: "50m"
        vault.hashicorp.com/agent-limits-cpu: ""
        vault.hashicorp.com/agent-inject-secret-config: "database/creds/webhook-api"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "database/creds/webhook-api"}}
          export TYPEORM_USERNAME="{{ .Data.username }}"
          export TYPEORM_PASSWORD="{{ .Data.password }}"
          {{- end }}
          {{- with secret "kv/data/database" }}
          export TYPEORM_PORT="{{ .Data.data.port }}"
          export TYPEORM_HOST="{{ .Data.data.hostname }}"
          {{- end }}
          export TYPEORM_DATABASE="webhook-api"
          {{- with secret "kv/data/queue" }}
          export QUEUE_URL="{{ .Data.data.url }}"
          {{- end }}
          {{- with secret "kv/data/webhook-api" }}
          export FIREBLOCKS_PUBLIC_KEY="{{ .Data.data.fireblocks_public_key }}"
          export AUTH0_WEBHOOK_SECRET="{{ .Data.data.auth0_secret_key }}"
          export PEACH_HMAC_SECRET="{{ .Data.data.peach_hmac_secret }}"
          {{- end }}
          `}}
      {{- end }}
    spec:
      serviceAccountName: webhook-api
      containers:
        - name: archie-webhook-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          args:
            ['sh', '-c', '. /vault/secrets/config && node service/main.js']
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
          {{- if not .Values.local }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_LOGS_INJECTION
              value: 'true'
          {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: archie-webhook-api-service
  labels:
    app: archie-webhook-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: archie-webhook-api
