apiVersion: apps/v1
kind: Deployment
metadata:
  name: archie-user-api
  labels:
    app: archie-user-api
    {{- if not .Values.local }}
    tags.datadoghq.com/env: '{{ .Values.environment }}'
    tags.datadoghq.com/service: 'archie-user-api'
    tags.datadoghq.com/version: '{{ .Values.tag }}'
    {{- end }}
spec:
  selector:
    matchLabels:
      app: archie-user-api
  {{- if not .Values.local }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: archie-user-api
        {{- if not .Values.local }}
        tags.datadoghq.com/env: '{{ .Values.environment }}'
        tags.datadoghq.com/service: 'archie-user-api'
        tags.datadoghq.com/version: '{{ .Values.tag }}'
        {{- else }}
        helm-revision: '{{ .Release.Revision }}'
        {{- end }}
    spec:
      containers:
        - name: archie-user-api
          image: '{{ .Values.image }}:{{ .Values.tag }}'
          {{- if not .Values.local }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: Never
          {{- end }}
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          {{- if not .Values.local }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_LOGS_INJECTION
              value: 'true'
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: domain
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: audience
            - name: AUTH0_M2M_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: m2m-client-id
            - name: AUTH0_M2M_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: m2m-client-secret
            - name: AUTH0_M2M_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-shared-secrets
                  key: m2m-domain
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: db-username
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: db-password
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: db-hostname
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: db-port
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: db-database
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: queue-shared-secrets
                  key: queue-url
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: user-api-secrets
                  key: encryption-key
            - name: DYNAMO_REGION
              valueFrom:
                secretKeyRef:
                  name: dynamodb-shared-secrets
                  key: region
            - name: DYNAMO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dynamodb-shared-secrets
                  key: access-key-id
            - name: DYNAMO_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: dynamodb-shared-secrets
                  key: access-key-secret
          {{- end }}
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: archie-user-api-service
  labels:
    app: archie-user-api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: archie-user-api
