name: 'Build UI'
description: 'Build UI and save artifacts'

inputs:
  projectName:
    description: 'Project name'
    required: true
  environment:
    description: 'Environment'
    required: true
  

runs:
  using: composite
  steps:
    - name: Configure build environment variables
      uses: ./.github/actions/set-ui-configuration
      with:
        projectName: ${{ inputs.projectName }}
        environment: ${{ inputs.environment }}
    - name: Build UI
      shell: bash
      env:
        NX_API_URL: ${{ env.NX_API_URL }}
        NX_WS_URL: ${{ env.NX_WS_URL }}
        NX_AUTH0_DOMAIN: ${{ env.NX_AUTH0_DOMAIN }}
        NX_AUTH0_CLIENT_ID: ${{ env.NX_AUTH0_CLIENT_ID }}
        NX_AUTH0_AUDIENCE: ${{ env.NX_AUTH0_AUDIENCE }}
      run: |
        npx nx run ${{ inputs.projectName }}:build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.projectName }}-build
        path: dist/apps/${{ inputs.projectName }}
