export const SERVICE_NAME = 'referral-system-api'
export const SERVICE_QUEUE_NAME = `${SERVICE_NAME}-queue`

export enum ConfigVariables {
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_PORT = 'TYPEORM_PORT',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_MAILING_LIST_ID = 'SENDGRID_MAILING_LIST_ID',
  SENDGRID_API_URL = 'SENDGRID_API_URL',
  SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID = 'SENDGRID_VERIFY_EMAIL_TEMPLATAE_ID',
  SENDGRID_WELCOME_EMAIL_TEMPLATE_ID = 'SENDGRID_WELCOME_EMAIL_TEMPLATE_ID',
  ARCHIE_MARKETING_WEBSITE_URL = 'ARCHIE_MARKETING_WEBSITE_URL',
  VAULT_PRIVATE_ADDRESS = 'VAULT_PRIVATE_ADDRESS',
  VAULT_USERNAME = 'VAULT_USERNAME',
  VAULT_PASSWORD = 'VAULT_PASSWORD',
  VAULT_NAMESPACE = 'VAULT_NAMESPACE',
}
