name: Check

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'patch/*'

env:
  AWS_REGION: us-east-1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Workspace lint
        run: npx nx workspace-lint
      - name: Format check
        run: npx nx format:check
      - name: Affected lint
        run: npx nx affected --target=lint --parallel=3
      - name: Affected test
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Affected build
        run: npx nx affected --target=build --parallel=3
