name: Check

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'patch/*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - name: Add github npm repository
        run: echo "@rizefinance:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Install dependencies
        run: npm i
      - name: Workspace lint
        run: npx nx workspace-lint
      # - name: Format check
      #   run: npx nx format:check
      - name: Affected lint
        run: npx nx affected --target=lint --parallel=3
      - name: Affected test
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Affected build
        run: npx nx affected --target=build --parallel=3
