name: Check

on:
  push:
    branches:
      - 'feature/*'
      - 'patch/*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development
    env:
      AUTH0_DOMAIN: auth.dev.archie.finance
      AUTH0_AUDIENCE: https://api.dev.archie.finance

      TYPEORM_HOST: host.minikube.internal
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TZ: UTC

      INTERNAL_API_URL: http://host.minikube.internal
      QUEUE_URL: amqp://host.minikube.internal

      APTO_API_KEY: ''
      APTO_API_URL: ''
      APTO_CARD_PROGRAME_ID: ''
      APTO_PUBLIC_KEY: ''
      APTO_PRIVATE_KEY: ''
      APTO_FUNDING_BALANCE_ID: ''

      RIZE_ENVIRONMENT: ''
      RIZE_PROGRAM_ID: ''
      RIZE_HMAC_KEY: ''
      RIZE_MQ_HOST: ''
      RIZE_MQ_TOPIC_PREFIX: ''
      RIZE_MQ_USERNAME: ''
      RIZE_MQ_PASSWORD: ''
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'develop'
      - uses: ./.github/actions/install-dependencies
        name: Install dependencies
      - name: Workspace lint
        run: npx nx workspace-lint
      - name: Affected lint
        run: npx nx affected --base=origin/develop --target=lint --parallel=3
      - name: Affected test
        run: npx nx affected --base=origin/develop --target=test --parallel=3 --ci --code-coverage
      - name: Affected build
        run: npx nx affected --base=origin/develop --target=build --parallel=3
