name: Deploy feature

on:
  push:
    tags:
      - v*-alpha
 
env:
  ECR_REPOSITORY: archie-development-container-repository
  AWS_REGION: us-east-1

jobs:
  workflow:
    uses: ./.github/workflows/deploy.yaml
    with:
      NAME: 'feature-deployment'
      IS_TAGGED: true
      ENVIRONMENT: development
      ECR_REPOSITORY: archie-development-container-repository
      AWS_REGION: us-east-1
      BASE_BRANCH_NAME: feature/rpc
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_DEVELOPMENT }}
