name: Development

on:
  push:
    branches:
      - feature/separate-deployments
 
env:
  ECR_REPOSITORY: archie-development-container-repository
  AWS_REGION: us-east-1

jobs:
  extract:
    name: Extract affected apps
    runs-on: ubuntu-latest
    environment: development
    outputs:
      affectedProjects: ${{ steps.affected-projects.outputs.affectedProjects }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch-depth: 0
    - uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: 'develop'
    - uses: ./.github/actions/install-dependencies
      name: Install dependencies
    - uses: ./.github/actions/affected-projects
      id: affected-projects
      name: Extract affected apps
      with:
        base: origin/main
  deploy:
    name: Deploy ${{ matrix.project }}
    needs: extract
    runs-on: ubuntu-latest
    environment: development
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.extract.outputs.affectedProjects) }}
    steps:
      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: FurlanLuka
      #     minimum-approvals: 1
      #     issue-title: "Deploy to development"
      - name: Poor mans manual deploy
        if: ${{ github.run_attempt== 1}}
        run: exit 1
      - name: Affected project name
        run: echo ${{ matrix.project }}