name: Deployment workflow

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      IS_TAGGED:
        required: true
        type: boolean
      ENVIRONMENT:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      BASE_BRANCH_NAME:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      KUBE_CONFIG_DATA:
        required: true

jobs:
  check_and_build:
    name: Check and Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      affectedProjects: ${{ steps.affected-projects.outputs.affectedProjects }}
      imageTag: ${{ steps.extract-image-tag.outputs.IMAGE_TAG }}
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
        ports:
          - 5672:5672
      redis:
        image: redis:alpine3.16
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        if: inputs.BASE_BRANCH_NAME == ''
      - uses: nrwl/nx-set-shas@v2
        if: inputs.BASE_BRANCH_NAME != ''
        with:
          main-branch-name: ${{ inputs.BASE_BRANCH_NAME }}
      - uses: ./.github/actions/install-dependencies
        name: Install dependencies
      - name: Workspace Lint
        run: npx nx workspace-lint
      - name: Prepare testing environment
        run: npx nx generate @archie/plugin/workspace-generator:test-environment-generator
      # - name: Affected Lint
      #   if: inputs.BASE_BRANCH_NAME == ''
      #   run: npx nx affected --target=lint --parallel=3
      # - name: Affected Lint
      #   if: inputs.BASE_BRANCH_NAME != ''
      #   run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=lint --parallel=3
      - name: Affected Integration Test
        if: inputs.BASE_BRANCH_NAME == ''
        run: npx nx affected --target=test-integration --parallel=3 --ci --code-coverage
      - name: Affected Integration Test
        if: inputs.BASE_BRANCH_NAME != ''
        run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=test-integration --parallel=3 --ci --code-coverage
      # - name: Affected Build
      #   if: inputs.BASE_BRANCH_NAME == ''
      #   run: npx nx affected --target=build --parallel=3
      # - name: Affected Build
      #   if: inputs.BASE_BRANCH_NAME != ''
      #   run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=build --parallel=3
      # - name: Store build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: services-build-${{ inputs.NAME }}
      #     path: ./dist
      #     retention-days: 1
      - uses: ./.github/actions/affected-projects
        id: affected-projects
        name: Extract affected apps
        with:
          base: origin/${{ inputs.BASE_BRANCH_NAME }}
      - name: Extract image tag
        id: extract-image-tag
        run: |
          if [[ ${{ inputs.IS_TAGGED }} == true ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          fi
  build_and_publish:
    name: Build ${{ matrix.project }}
    if: ${{ needs.check_and_build.outputs.affectedProjects != '[]' && needs.check_and_build.outputs.affectedProjects != '' }}
    needs: [check_and_build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check_and_build.outputs.affectedProjects) }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: ./.github/actions/install-dependencies
        name: Install dependencies
      - if: contains(matrix.project, 'api')
        uses: ./.github/actions/publish-docker-image
        name: Build and publish docker image
        with:
          projectName: ${{ matrix.project }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
          ecr-repository: ${{ inputs.ECR_REPOSITORY }}
          image-tag: ${{ needs.check_and_build.outputs.imageTag }}
      - if: contains(matrix.project, 'ui')
        uses: ./.github/actions/build-ui
        name: Build UI and save artifacts
        with:
          projectName: ${{ matrix.project }}
          environment: ${{ inputs.ENVIRONMENT }}
  deploy:
    name: Deploy ${{ matrix.project }}
    if: ${{ needs.check_and_build.outputs.affectedProjects != '[]' && needs.check_and_build.outputs.affectedProjects != '' }}
    needs: [build_and_publish, check_and_build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check_and_build.outputs.affectedProjects) }}
    steps:
    - name: Poor mans manual deploy
      if: ${{ github.run_attempt== 1}}
      run: exit 1
    - uses: actions/checkout@v2
      name: Checkout
    - uses: ./.github/actions/install-dependencies
      name: Install dependencies
    - if: contains(matrix.project, 'api')
      uses: ./.github/actions/deploy-api
      name: Deploy API
      with:
        projectName: ${{ matrix.project }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
        ecr-repository: ${{ inputs.ECR_REPOSITORY }}
        kube-config-data: ${{ secrets.KUBE_CONFIG_DATA }}
        environment: ${{ inputs.ENVIRONMENT }}
        image-tag: ${{ needs.check_and_build.outputs.imageTag }}
    - if: contains(matrix.project, 'ui')
      uses: ./.github/actions/deploy-ui
      name: Deploy UI
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
        projectName: ${{ matrix.project }}
        environment: ${{ inputs.ENVIRONMENT }}
