name: Deployment workflow

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      IS_TAGGED:
        required: true
        type: boolean
      ENVIRONMENT:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      BASE_BRANCH_NAME:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      KUBE_CONFIG_DATA:
        required: true

jobs:
  check_and_build:
    name: Check and Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      affectedProjects: ${{ steps.affected-projects.outputs.affectedProjects }}
      imageTag: ${{ steps.extract-image-tag.outputs.IMAGE_TAG }}

    env:
      # GLOBAL
      AUTH0_DOMAIN: auth.dev.archie.finance
      AUTH0_AUDIENCE: https://api.dev.archie.finance

      TYPEORM_HOST: localhost
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TZ: UTC

      INTERNAL_API_URL: http://localhost
      QUEUE_URL: amqp://localhost

      ENCRYPTION_KEY: ')J@McQfTjWnZr4u7x!A%D*G-KaPdRgUk'

      # CREDIT API
      APTO_API_KEY: ''
      APTO_API_URL: ''
      APTO_CARD_PROGRAME_ID: ''
      APTO_PUBLIC_KEY: ''
      APTO_PRIVATE_KEY: ''
      APTO_FUNDING_BALANCE_ID: ''

      RIZE_ENVIRONMENT: 'sandbox'
      RIZE_PROGRAM_ID: 'test'
      RIZE_HMAC_KEY: 'test'
      RIZE_MQ_HOST: 'test'
      RIZE_MQ_TOPIC_PREFIX: 'test'
      RIZE_MQ_USERNAME: 'test'
      RIZE_MQ_PASSWORD: 'test'

      ## Peach api
      PEACH_API_KEY: 'test'
      PEACH_BASE_URL: 'https://sandboxapi.peach.finance/api'
      PEACH_COMPANY_ID: 'CP-25K9-4GJ6'
      PEACH_BORROWER_ROLE_ID: 'RL-G2K6-NLK4'
      PEACH_LOAN_ID: 'LT-GDB3-WEBO'
      API_BASE_URL: 'http://localhost'
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        if: inputs.BASE_BRANCH_NAME == ''
      - uses: nrwl/nx-set-shas@v2
        if: inputs.BASE_BRANCH_NAME != ''
        with:
          main-branch-name: ${{ inputs.BASE_BRANCH_NAME }}
      - uses: ./.github/actions/install-dependencies
        name: Install dependencies
      - name: Workspace Lint
        run: npx nx workspace-lint
      - name: Affected Lint
        if: inputs.BASE_BRANCH_NAME == ''
        run: npx nx affected --target=lint --parallel=3
      - name: Affected Lint
        if: inputs.BASE_BRANCH_NAME != ''
        run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=lint --parallel=3
      - name: Affected Test
        if: inputs.BASE_BRANCH_NAME == ''
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Affected Test
        if: inputs.BASE_BRANCH_NAME != ''
        run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=test --parallel=3 --ci --code-coverage
      - name: Affected Build
        if: inputs.BASE_BRANCH_NAME == ''
        run: npx nx affected --target=build --parallel=3
      - name: Affected Build
        if: inputs.BASE_BRANCH_NAME != ''
        run: npx nx affected --base=origin/${{ inputs.BASE_BRANCH_NAME }} --target=build --parallel=3
      - name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: services-build-${{ inputs.NAME }}
          path: ./dist
          retention-days: 1
      - uses: ./.github/actions/affected-projects
        id: affected-projects
        name: Extract affected apps
        with:
          base: origin/${{ inputs.BASE_BRANCH_NAME }}
      - name: Extract image tag
        id: extract-image-tag
        run: |
          if [[ ${{ inputs.IS_TAGGED }} == true ]]; then
            echo ::set-output name=IMAGE_TAG::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=IMAGE_TAG::$(git rev-parse HEAD)
          fi
  build_and_publish:
    name: Build ${{ matrix.project }} docker
    if: ${{ needs.check_and_build.outputs.affectedProjects != '[]' && needs.check_and_build.outputs.affectedProjects != '' }}
    needs: [check_and_build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check_and_build.outputs.affectedProjects) }}
    steps:
      - name: Poor mans manual trigger
        if: ${{ github.run_attempt == 1}}
        run: exit 1
      - uses: actions/checkout@v2
        name: Checkout
      - uses: ./.github/actions/install-dependencies
        name: Install dependencies
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: services-build-${{ inputs.NAME }}
          path: ./dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker build
        env:
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.check_and_build.outputs.imageTag }}
        run: |
          npx nx run ${{ matrix.project }}:build-docker --ecrRegistry=$ECR_REGISTRY --ecrRepository=$ECR_REPOSITORY --imageTag=$IMAGE_TAG
  deploy:
    name: Deploy ${{ matrix.project }}
    if: ${{ needs.check_and_build.outputs.affectedProjects != '[]' && needs.check_and_build.outputs.affectedProjects != '' }}
    needs: [build_and_publish, check_and_build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.check_and_build.outputs.affectedProjects) }}
    steps:
    - name: Poor mans manual deploy
      if: ${{ github.run_attempt== 1}}
      run: exit 1
    - uses: actions/checkout@v2
      name: Checkout
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Deploy
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ matrix.project }}-${{ needs.check_and_build.outputs.imageTag }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        CHART: ./apps/${{ matrix.project }}/chart
        APP_NAME: ${{ matrix.project }}
      with:
        command: helm upgrade --install $APP_NAME $CHART --set tag=$IMAGE_TAG --set image=$ECR_REGISTRY/$ECR_REPOSITORY --set environment=$ENVIRONMENT
