name: Development

on:
  push:
    branches:
      - "test-helm-action"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-dependencies
      name: Install dependencies
    - name: Affected deploy
      uses: ./.github/actions/node-helm
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_DEVELOPMENT }}
      with:
        args: --base=origin/main --target=deploy --ecrRegistry=${{ steps.login-ecr.outputs.registry }} --ecrRepository=${{ env.ECR_REPOSITORY }} --imageTag=${{ steps.git_details.outputs.COMMIT_HASH }} --environment=development
